// Localized strings for UI elements
export const strings = {
  en: {
    selectLanguage: 'Select Language',
    tapToSpeak: 'Tap and hold the microphone to start speaking...',
    recording: 'Recording...',
    processing: 'Processing...',
    recordingError: 'Recording Error',
    failedToStartRecording: 'Failed to start recording',
    translationError: 'Translation Error',
    failedToTranslateSpeech: 'Failed to translate speech',
  },
  es: {
    selectLanguage: 'Seleccionar idioma',
    tapToSpeak: 'Mantén presionado el micrófono para comenzar a hablar...',
    recording: 'Grabando...',
    processing: 'Procesando...',
    recordingError: 'Error de grabación',
    failedToStartRecording: 'No se pudo iniciar la grabación',
    translationError: 'Error de traducción',
    failedToTranslateSpeech: 'No se pudo traducir el discurso',
  },
  fr: {
    selectLanguage: 'Sélectionner la langue',
    tapToSpeak: 'Appuyez et maintenez le microphone pour commencer à parler...',
    recording: 'Enregistrement...',
    processing: 'Traitement...',
    recordingError: 'Erreur d\'enregistrement',
    failedToStartRecording: 'Impossible de démarrer l\'enregistrement',
    translationError: 'Erreur de traduction',
    failedToTranslateSpeech: 'Impossible de traduire la parole',
  },
  de: {
    selectLanguage: 'Sprache auswählen',
    tapToSpeak: 'Halten Sie das Mikrofon gedrückt, um zu sprechen...',
    recording: 'Aufnahme...',
    processing: 'Verarbeitung...',
    recordingError: 'Aufnahmefehler',
    failedToStartRecording: 'Aufnahme konnte nicht gestartet werden',
    translationError: 'Übersetzungsfehler',
    failedToTranslateSpeech: 'Sprache konnte nicht übersetzt werden',
  },
  it: {
    selectLanguage: 'Seleziona lingua',
    tapToSpeak: 'Tieni premuto il microfono per iniziare a parlare...',
    recording: 'Registrazione...',
    processing: 'Elaborazione...',
    recordingError: 'Errore di registrazione',
    failedToStartRecording: 'Impossibile avviare la registrazione',
    translationError: 'Errore di traduzione',
    failedToTranslateSpeech: 'Impossibile tradurre il discorso',
  },
  pt: {
    selectLanguage: 'Selecionar idioma',
    tapToSpeak: 'Mantenha pressionado o microfone para começar a falar...',
    recording: 'Gravando...',
    processing: 'Processando...',
    recordingError: 'Erro de gravação',
    failedToStartRecording: 'Falha ao iniciar gravação',
    translationError: 'Erro de tradução',
    failedToTranslateSpeech: 'Falha ao traduzir fala',
  },
  ru: {
    selectLanguage: 'Выберите язык',
    tapToSpeak: 'Нажмите и удерживайте микрофон, чтобы начать говорить...',
    recording: 'Запись...',
    processing: 'Обработка...',
    recordingError: 'Ошибка записи',
    failedToStartRecording: 'Не удалось начать запись',
    translationError: 'Ошибка перевода',
    failedToTranslateSpeech: 'Не удалось перевести речь',
  },
  ja: {
    selectLanguage: '言語を選択',
    tapToSpeak: 'マイクを長押しして話し始めてください...',
    recording: '録音中...',
    processing: '処理中...',
    recordingError: '録音エラー',
    failedToStartRecording: '録音を開始できませんでした',
    translationError: '翻訳エラー',
    failedToTranslateSpeech: '音声を翻訳できませんでした',
  },
  ko: {
    selectLanguage: '언어 선택',
    tapToSpeak: '마이크를 길게 눌러서 말하기 시작하세요...',
    recording: '녹음 중...',
    processing: '처리 중...',
    recordingError: '녹음 오류',
    failedToStartRecording: '녹음을 시작할 수 없습니다',
    translationError: '번역 오류',
    failedToTranslateSpeech: '음성을 번역할 수 없습니다',
  },
  zh: {
    selectLanguage: '选择语言',
    tapToSpeak: '按住麦克风开始说话...',
    recording: '录音中...',
    processing: '处理中...',
    recordingError: '录音错误',
    failedToStartRecording: '无法开始录音',
    translationError: '翻译错误',
    failedToTranslateSpeech: '无法翻译语音',
  },
  ar: {
    selectLanguage: 'اختر اللغة',
    tapToSpeak: 'اضغط مع الاستمرار على الميكروفون لبدء التحدث...',
    recording: 'جاري التسجيل...',
    processing: 'جاري المعالجة...',
    recordingError: 'خطأ في التسجيل',
    failedToStartRecording: 'فشل في بدء التسجيل',
    translationError: 'خطأ في الترجمة',
    failedToTranslateSpeech: 'فشل في ترجمة الكلام',
  },
  hi: {
    selectLanguage: 'भाषा चुनें',
    tapToSpeak: 'बोलना शुरू करने के लिए माइक्रोफ़ोन को दबाकर रखें...',
    recording: 'रिकॉर्डिंग...',
    processing: 'प्रसंस्करण...',
    recordingError: 'रिकॉर्डिंग त्रुटि',
    failedToStartRecording: 'रिकॉर्डिंग शुरू करने में विफल',
    translationError: 'अनुवाद त्रुटि',
    failedToTranslateSpeech: 'भाषण का अनुवाद करने में विफल',
  },
};

export function getString(languageCode: string, key: keyof typeof strings.en): string {
  const languageStrings = strings[languageCode as keyof typeof strings];
  if (languageStrings && languageStrings[key]) {
    return languageStrings[key];
  }
  // Fallback to English if translation not found
  return strings.en[key];
}